=== DeepCyclone/JWD_Parsers/target/test-classes/banks.xsd
<?xml version = "1.0" encoding = "UTF-8"?>
<!--
	 schema - корневой, прописан в XMLSchema (xmlns - keyword)
 	 targetNamespace - задаём наше пространство
 	 tns - обозначаем наше пространство
-->
<schema xmlns = "http://www.w3.org/2001/XMLSchema"
				targetNamespace="http://www.example.com/banks"
				xmlns:tns="http://www.example.com/banks"
				elementFormDefault="qualified">

<!-- определение иерархии наследования-->

<element name="bank" type="tns:Bank" abstract="true"/>
<element name="commercialBank" type="tns:commercialBank" substitutionGroup="tns:bank"/>
<element name="nationalBank" type="tns:nationalBank" substitutionGroup="tns:bank"/>

<!--  корневой элемент -->
<element name = "banks">
	<complexType>
		<sequence>
			<!-- просто ссылаемся на абстрактный элемент -->
			<element ref="tns:bank"
					 minOccurs = "0"
					 maxOccurs = "unbounded"/>
		</sequence>
	</complexType>
</element>

	<!-- начало объявления типов, находящихся в простанстве имён banks (не указываем его, т.к. elementFormDefault установлен в qualified) -->

	<complexType name = "Bank">

		<!-- all,sequence,choice-->
		<sequence>
			<element name = "name" type = "string"/>
			<element name = "lastCurrencyUpdate" type="tns:lastCurrencyUpdate"/>
		</sequence>

		<attribute name = "country" type = "string" use = "optional" default="USA"/>


	</complexType>

	<!-- наследование от типа Bank -->
	<complexType name="commercialBank">
		<complexContent>
			<extension base="tns:Bank">
				<sequence>
					<element name = "type" type = "tns:Type"/>
					<element name = "accountID" type = "tns:accountID"/>
					<element name = "amountOnDeposit" type = "tns:amountOnDeposit"/>
					<element name = "hasSpecifiedAccounts" type="boolean"/>
					<element name = "Profitability" type = "decimal"/>
					<element name = "timeConstraints" type = "integer"/>
				</sequence>
				<attribute name = "depositor" type = "string" use = "required"/>
			</extension>
		</complexContent>
	</complexType>
	
	<complexType name="nationalBank">
		<complexContent>
			<extension base="tns:Bank">
				<sequence>
					<element name="canEmitMoney" type="boolean"/>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<simpleType name = "Type" final = "restriction">
		<restriction base = "string">
			<enumeration value = "beforeDemand"/>
			<enumeration value = "urgent"/>
			<enumeration value = "counted"/>
			<enumeration value = "collecting"/>
			<enumeration value = "saving"/>
			<enumeration value = "metallic"/>
		</restriction>
	</simpleType>

	<simpleType name="accountID">
		<restriction base="ID">
			<pattern value="[BUCSM]\d{5}"/>
		</restriction>
	</simpleType>

	<simpleType name="lastCurrencyUpdate">
		<restriction base="dateTime">
			<pattern value="(20[01][0-9]|202[0-1])-(0[1-9]|1[0-2])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-4]):([0-6][0-9]):([0-6][0-9])"/>
		</restriction>
	</simpleType>

	<simpleType name="amountOnDeposit">
		<restriction base="decimal">
			<maxInclusive value="200.123"/>
			<maxInclusive value="555.55"/>
		</restriction>
	</simpleType>

	</schema>

=== DeepCyclone/JWD_Parsers/target/test-classes/mixedBanks.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.com/banks"
	xsi:schemaLocation="http://www.example.com/banks banks.xsd">

	<nationalBank>
		<name>SB</name>
		<lastCurrencyUpdate>2021-05-24T10:59:59</lastCurrencyUpdate>
		<canEmitMoney>true</canEmitMoney>
	</nationalBank>

	<commercialBank depositor="Flexus">
		<name>RF Bank Inc</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>urgent</type>
		<accountID>U22222</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

</banks>

=== DeepCyclone/JWD_Parsers/src/test/resources/CommercialBank.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.com/banks"
	xsi:schemaLocation="http://www.example.com/banks banks.xsd">

	<commercialBank depositor="FBI" country="USA">
		<name>Colk Bank Inc</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>beforeDemand</type>
		<accountID>B27622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

</banks>

=== DeepCyclone/JWD_Parsers/target/classes/banks.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<banks xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.com/banks"
	xsi:schemaLocation="http://www.example.com/banks banks.xsd">

	<nationalBank>
		<name>SB</name>
		<lastCurrencyUpdate>2021-05-24T10:59:59</lastCurrencyUpdate>
		<canEmitMoney>true</canEmitMoney>
	</nationalBank>

	<nationalBank>
		<name>UB</name>
		<lastCurrencyUpdate>2021-06-24T19:59:59</lastCurrencyUpdate>
		<canEmitMoney>false</canEmitMoney>
	</nationalBank>

	<nationalBank>
		<name>UB</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<canEmitMoney>true</canEmitMoney>
	</nationalBank>

	<commercialBank depositor="Flexus">
		<name>RF Bank Inc</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>urgent</type>
		<accountID>U22222</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="FBI" country="USA">
		<name>Colk Bank Inc</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>beforeDemand</type>
		<accountID>B27622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="Tom">
		<name>Invest Bank</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>metallic</type>
		<accountID>M27622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="ABC" country="Sweden">
		<name>Private bank Sweden</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>saving</type>
		<accountID>S27622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="CBA">
		<name>Limited Bank UK</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>collecting</type>
		<accountID>C27622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="OPC">
		<name>US Focused bank group</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>counted</type>
		<accountID>C27665</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="Fixic">
		<name>Moscow Invest Bank</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>beforeDemand</type>
		<accountID>B24622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="User">
		<name>Palomino Crack</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>saving</type>
		<accountID>S27422</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="GoldHolder">
		<name>California open Bank</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>collecting</type>
		<accountID>C27672</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="BMan">
		<name>WorldWide Bank Hungary partner</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>beforeDemand</type>
		<accountID>B37622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="Boris" country="Poland">
		<name>East-European Bank of Building in Poland</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>metallic</type>
		<accountID>M47622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="Undefined">
		<name>Technical bank of Silicon Valley</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>metallic</type>
		<accountID>M57622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="Gregory">
		<name>Chinese bank</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>beforeDemand</type>
		<accountID>B22622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

	<commercialBank depositor="Lekko">
		<name>Last</name>
		<lastCurrencyUpdate>2021-08-22T16:59:59</lastCurrencyUpdate>
		<type>collecting</type>
		<accountID>C77622</accountID>
		<amountOnDeposit>132</amountOnDeposit>
		<hasSpecifiedAccounts>true</hasSpecifiedAccounts>
		<Profitability>345</Profitability>
		<timeConstraints>2222</timeConstraints>
	</commercialBank>

</banks>
